version: "3.7"

services:
  frontend:
    build:
      context: src/python
    image: frontend
    environment:
      - REDIS_HOST=redis
      - NEXT_URL=http://middle:8080/api
    ports:
    - 8080:8080

  middle:
    build:
      context: src/nodejs
    image: middleware
    environment:
      - NEXT_URL=http://backend:8080/api
    ports:
    - 8082:8080

  backend:
    build:
      context: src/go
    image: backend
    ports:
    - 8086:8080

  redis:
    image: redis:alpine
