version: "3.0"

services:
  anyApp:
    build:
      context: src/${PROJECT_LANG:-python}
    image: ${DOCKER_REPO:-mcano}/${PROJECT_LANG:-python}-expert:v${VERSION:-1.0}
    environment:
      - FOO=bar
      - VAR=var
      - REDIS_HOST=db
    ports:
      - 80:8080
    logging:
      driver: awslogs
      options:
        awslogs-group: ec2-tutorial
        awslogs-region: us-west-2
        awslogs-stream-prefix: web

# # FQDN == fully qualified domain name
  # db:
  #   image: redis:alpine
  #   restart: on-failure


