apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apache
  labels:
    name:  web-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name:  my-name
  template:
    metadata:
      labels:
        name:  my-name
    spec:
      containers:
      - image:  httpd
        name:  apache
        resources:
          # idle
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "500m"
            memory: "500M"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE
        ports:
        - containerPort:  80
          name:  http
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name:  apache
spec:
  selector:
    name:  my-name
  type:   NodePort
  ports:
  - name:  web
    port:  80
    targetPort:  http
    #nodePort: 32490
