version: "3.0"



services:
  anyApp:
    build:
      context: src/${PROJECT_LANG:-python}
    image: ${DOCKER_REPO:-mcano}/${PROJECT_LANG:-python}-expert:v${VERSION:-1.0}
    environment:
      - FOO=bar
      - VAR=var
      - REDIS_HOST=db
    volumes:
    # bind volume
      - ./src/python/:/code
    working_dir: /code
    command: ["sh", "-c", "pip install -r requirements.txt && python app.py"]
    ports:
      - 8080:8080

# FQDN == fully qualified domain name
  db:
    image: redis:alpine
    restart: on-failure


